version: "3.8"

services:
  backend:
    image: yourdockerhubuser/asana-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=asana_auth
      - POSTGRES_USER=asana_user
      - POSTGRES_PASSWORD=asana_pass
    depends_on:
      - postgres
    volumes:
      - ./ontology_updated.owl:/app/ontology_updated.owl

  frontend:
    image: yourdockerhubuser/asana-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: asana_auth
      POSTGRES_USER: asana_user
      POSTGRES_PASSWORD: asana_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

volumes:
  pgdata: 